matrix:
    include:
      - language: java
        java: 11
        before_script:
          - cd back
        script:
          - mvn clean install
  
      - language: node_js
        node_js: 14
        before_script:
          - cd front
        script:
          - npm install
          - npm run lint
          - npm run build
  

notifications:
  slack: informatiquep-kyw7477:drzHOWQ9ow9kLfoGYeCvpsVN