matrix:
    include:
      - language: java
        java: 11
        services:
          - mysql
        before_install:
          - mysql -e 'CREATE DATABASE tmtravis;'
        before_script:
          - cd back
        script:
          - mvn clean install -Ptravis
  
      - language: node_js
        node_js: 14
        before_script:
          - cd front
        script:
          - npm install
          - npm run lint
          - npm run build
      
      - language: java
        java: 11
        services: 
          - docker
        before_script:
          - nvm install 14 # for Node v5
        script:
          - cd docker
          - ./compose.sh
        if: branch = ci or branch = master or branch = release

notifications:
  slack: informatiquep-kyw7477:drzHOWQ9ow9kLfoGYeCvpsVN