server:
    port: 3000
    servlet:
        encoding:
            force-response: true
            charset: UTF-8

spring:
    datasource:
        url: jdbc:mysql://database:3306/tmdocker?serverTimezone=Europe/Paris
        username: user
        password: password
        driver-class-name: com.mysql.jdbc.Driver
    
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true

env:
    mode: dev