FROM nginx

# Setting working directory. All the path will be relative to WORKDIR
# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/share/nginx/html

# Copying source files
COPY ./dist .

EXPOSE 8080